### PR TITLE
Seed-based randomized test order

### LINKED ISSUE #62: Tests fail depending on their order
On the latest revision of the code base, tests will fail around 10-20% of the time, depending on their order. It's hard to trace the reason why, since each time the tests are run, their order is different.

As an idea, it would be useful to be able to choose the order of the tests. And for this order to be printed whenever it's randomly generated.

### PR DESCRIPTION
**Pull request by fayalalebrun**
Added the option to give a seed for the test order randomizer. If no seed is given, the time is used as a seed. The seed being used is also printed beforehand, which is useful when trying to replicate the order in which tests are run.

Related to #62

### CODE REVIEW

File: kernel/src/test/generate_tests.sh [hunk 1]
```diff
@@ -4,6 +4,14 @@
 # the makefile will run this file automatically while building,
 # so all tests are automatically executed.
 
+# https://www.gnu.org/software/coreutils/manual/html_node/Random-sources.html
+get_seeded_random()
+{
+  seed="$1"
+  openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt \
```
Comment (jonay2000) [inline kernel/src/test/generate_tests.sh:11]: Now we need openssl as dep. And we don't need crypto security anyway. But to prevent --random-source being too short maybe use sha256sum as it's in coreutils which is a but more likely to be on a system.

**Review by jonay2000 — APPROVED** [review]
Apart from this, I think it's a great addition. Good first PR!

File: kernel/src/test/generate_tests.sh (hunk 1 above)
Comment (ValentijnvdBeek) [reply kernel/src/test/generate_tests.sh:11]: I think that using /dev/urandom or /dev/random here would be the best option, the security of the randomness doesn't really matter and we only run the command once.

Comment (jonay2000) [reply kernel/src/test/generate_tests.sh:11]: Yea, but if you use a seed, and the seed is too short, it wouldn't work. openssl pads it to a fixed length, and so wout sha256sum. But indeed, when we're not seeding it, /dev/urandom is fine

**Comment by jonay2000** [comment]
I merged @ValentijnvdBeeks PR first, but it came with some conflicts. If someone fixes them I'll merge this one as well
